---
- name: Install passenger gem
  gem: name=passenger version=5.0.20 state=present user_install=no

- name: Setup passenger in rc.local (so app comes back on reboot)
  lineinfile: dest=/etc/rc.d/rc.local state=present line="cd /home/{{ app_name }}/app && /usr/local/rvm/bin/rvm-exec `rvm current` passenger start current"

- name: Start Passenger app
  shell: /usr/local/rvm/bin/rvm-exec `rvm current` passenger start current chdir=/home/{{ app_name }}/app
  ignore_errors: yes # in case the app is already running
