---
- name: Get current Ruby
  command: /usr/local/rvm/bin/rvm current
  register: current_ruby

- name: Install passenger gem
  gem: name=passenger version=5.0.23 state=present user_install=no executable="/usr/local/rvm/bin/rvm-exec {{ current_ruby.stdout }} gem"

- name: Setup Passenger in rc.local (so app comes back on reboot)
  lineinfile: dest=/etc/rc.d/rc.local state=present line="cd /home/{{ app_name }}/app && /usr/local/rvm/bin/rvm-exec {{ current_ruby.stdout }} passenger start current"

- name: Start Passenger app
  shell: /usr/local/rvm/bin/rvm-exec {{ current_ruby.stdout }} passenger start current chdir=/home/{{ app_name }}/app
  ignore_errors: yes # in case the app is already running
